
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wivnusgagvdgjawknuwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpdm51c2dhZ3ZkZ2phd2tudXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjI0OTAsImV4cCI6MjA2NDAzODQ5MH0.3zu6-UfePnklSt_2HvbojXab-Pt_FTqoHrmJIzs_Dgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: 'pkce',
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
